Feature/wip
Byndyusoft/byndyusoft-net-rabbitmqconsumer-template pull request #1
Opened 2022-10-26 08:31 UTC by YuriyatByndyusoft

правки по фидбеку от Димы

2022-10-26 14:11 UTC, litichevskiydv requested changes

2022-10-26 14:11 UTC, litichevskiydv commented on template/.template.config/template.json
> +		"D230A5C0-6D02-4EE0-97E4-AAE950E7BD66"
Расскажи, пожалуйста, зачем мы их реплейсим?

2022-10-26 14:11 UTC, litichevskiydv commented on template/src/Contracts/Contracts.csproj
> +    <LangVersion>10</LangVersion>
Не хватает `AssemblyName` и `RootNamespace`, сейчас в не зависимости от итогового имени проекта это будет сборка Contracts.dll, что не хорошо

2022-10-26 14:11 UTC, litichevskiydv commented on template/src/RabbitMqConsumerTemplate/Infrastructure/Metrics/ApplicationBuilderExtensions.cs
> +    public static IApplicationBuilder UseRequestsMetrics(this IApplicationBuilder app)
Это стоит удалить, поскольку у нас только слжебные методы API,  к тому же, с переходом на OpenTelemetry этот код стал не нуным и в шаблоне API

2022-10-26 14:11 UTC, litichevskiydv commented on template/src/RabbitMqConsumerTemplate/Infrastructure/Swagger/ApplicationBuilderExtensions.cs
> +    public static IApplicationBuilder UseSwagger(
Нам это не нужно здесь, поскольку это не API, а воркер, у которого есть только метрики и health check, swagger будет всегда пустым

2022-10-26 14:11 UTC, litichevskiydv commented on template/src/RabbitMqConsumerTemplate/Infrastructure/Swagger/ConfigureSwaggerOptions.cs
> +public class ConfigureSwaggerOptions : IConfigureOptions<SwaggerGenOptions>
Нам это не нужно здесь, поскольку это не API, а воркер, у которого есть только метрики и health check, swagger будет всегда пустым

2022-10-26 14:11 UTC, litichevskiydv commented on template/src/RabbitMqConsumerTemplate/Infrastructure/Swagger/ServiceCollectionExtensions.cs
> +public static class ServiceCollectionExtensions
Нам это не нужно здесь, поскольку это не API, а воркер, у которого есть только метрики и health check, swagger будет всегда пустым

2022-10-26 14:11 UTC, litichevskiydv commented on template/src/RabbitMqConsumerTemplate/Infrastructure/Versioning/ServiceCollectionExtensions.cs
> +public static class ServiceCollectionExtensions
Нам это не нужно здесь, поскольку это не API, а воркер, поэтому никаких версий API тут не будет

2022-10-26 14:11 UTC, litichevskiydv commented on template/src/RabbitMqConsumerTemplate/Properties/launchSettings.json
> +        "launchUrl": "swagger",
По этому урлу ничего не будет, предлагаю убрать запуск браузера

2022-10-26 14:11 UTC, litichevskiydv commented on template/src/RabbitMqConsumerTemplate/RabbitMqConsumerTemplate.csproj
> +    <GenerateDocumentationFile>True</GenerateDocumentationFile>
Не хватае `AssemblyName` и `RootNamespace`, а `GenerateDocumentationFile` видится лишним, поскольку в приложении не будет контроллеров

2022-10-26 14:11 UTC, litichevskiydv commented on template/src/RabbitMqConsumerTemplate/Startup.cs
> +            .AddSwagger();
Это стоит удалить, поскольку у нас нет контроллеров

2022-10-26 14:11 UTC, litichevskiydv commented on template/src/RabbitMqConsumerTemplate/Startup.cs
> +            app.UseSwagger(apiVersionDescriptionProvider);
Это стоит удалить, поскольку у нас нет контроллеров

2022-10-26 14:11 UTC, litichevskiydv commented on template/src/RabbitMqConsumerTemplate/Startup.cs
> +           .UseEndpoints(endpoints => endpoints.MapControllers());
У нас нет контроллеров, потому не стоит их мапить

2022-10-26 14:11 UTC, litichevskiydv commented on template/tests/UnitTests/MessageHandlerTests.cs
> +    [Test]
Стоит договориться, какой фреймворк мы используем для написания тестов, в шаблоне API использован xUnit

2022-10-26 14:11 UTC, litichevskiydv commented on template/tests/UnitTests/UnitTests.csproj
> +    <Nullable>enable</Nullable>
Нужно добавить `AssemblyName` и `RootNamespace`

2022-10-27 08:24 UTC, YuriyatByndyusoft commented on template/src/RabbitMqConsumerTemplate/Infrastructure/Metrics/ApplicationBuilderExtensions.cs
> +    public static IApplicationBuilder UseRequestsMetrics(this IApplicationBuilder app)
Удалил.

2022-10-27 08:32 UTC, YuriyatByndyusoft commented on template/src/RabbitMqConsumerTemplate/Infrastructure/Swagger/ApplicationBuilderExtensions.cs
> +    public static IApplicationBuilder UseSwagger(
Убрал.

2022-10-27 08:34 UTC, YuriyatByndyusoft commented on template/src/RabbitMqConsumerTemplate/Startup.cs
> +            .AddSwagger();
Удалил

2022-10-27 08:34 UTC, YuriyatByndyusoft commented on template/src/RabbitMqConsumerTemplate/Startup.cs
> +            app.UseSwagger(apiVersionDescriptionProvider);
Удалил

2022-10-27 08:40 UTC, YuriyatByndyusoft commented on template/src/RabbitMqConsumerTemplate/Startup.cs
> +           .UseEndpoints(endpoints => endpoints.MapControllers());
Убрал.

2022-10-27 08:46 UTC, YuriyatByndyusoft commented on template/.template.config/template.json
> +		"D230A5C0-6D02-4EE0-97E4-AAE950E7BD66"
С учётом того, что они фигурируют только в .sln файле, то да, не имеет смысла, убрал.

2022-10-27 08:47 UTC, YuriyatByndyusoft commented on template/src/RabbitMqConsumerTemplate/Infrastructure/Swagger/ConfigureSwaggerOptions.cs
> +public class ConfigureSwaggerOptions : IConfigureOptions<SwaggerGenOptions>
Убрал.

2022-10-27 09:59 UTC, YuriyatByndyusoft commented on template/src/Contracts/Contracts.csproj
> +    <LangVersion>10</LangVersion>
Поправил

2022-10-27 10:04 UTC, YuriyatByndyusoft commented on template/src/RabbitMqConsumerTemplate/Properties/launchSettings.json
> +        "launchUrl": "swagger",
Убрал

2022-10-27 10:10 UTC, YuriyatByndyusoft commented on template/src/RabbitMqConsumerTemplate/RabbitMqConsumerTemplate.csproj
> +    <GenerateDocumentationFile>True</GenerateDocumentationFile>
Убрал GenerateDocumentationFile. Какой AssemblyName, RootNamespace лучше использовать? Сейчас они просто подтягивают заданное название сервиса.

2022-10-27 10:12 UTC, YuriyatByndyusoft commented on template/tests/UnitTests/MessageHandlerTests.cs
> +    [Test]
Кажется, что это - область ответственности команды на проекте? Поменять в шаблоне на xUnit?

2022-10-27 10:14 UTC, YuriyatByndyusoft commented on template/src/RabbitMqConsumerTemplate/Infrastructure/Swagger/ServiceCollectionExtensions.cs
> +public static class ServiceCollectionExtensions
Убрал

2022-10-27 10:15 UTC, YuriyatByndyusoft commented on template/tests/UnitTests/UnitTests.csproj
> +    <Nullable>enable</Nullable>
Добавил

2022-11-02 12:18 UTC, litichevskiydv requested changes

2022-11-02 12:18 UTC, litichevskiydv commented on template/src/RabbitMqConsumerTemplate/RabbitMqConsumerTemplate.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
Укажи явно `RootNamespace` и `AssemblyName`

2022-11-02 12:18 UTC, litichevskiydv commented on template/src/RabbitMqConsumerTemplate/RabbitMqConsumerTemplate.csproj
> +	<PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.3.1" />
Поправь форматирование

2022-11-07 05:23 UTC, YuriyatByndyusoft commented on template/src/RabbitMqConsumerTemplate/RabbitMqConsumerTemplate.csproj
> +    <ImplicitUsings>enable</ImplicitUsings>
Добавил

2022-11-07 05:23 UTC, YuriyatByndyusoft commented on template/src/RabbitMqConsumerTemplate/RabbitMqConsumerTemplate.csproj
> +	<PackageReference Include="OpenTelemetry.Exporter.Jaeger" Version="1.3.1" />
Поправил

2022-11-23 12:06 UTC, Satem commented
Меня беспокоит, что до начала использования пользователю шаблона нужно сделать определённые действия: добавить логику в MessageHandler, изменить название очереди и эксчейнджа, изменить/добавить свойства в MessageContract. Это нужно сделать в разных местах, а мы никак явным образом не "тыкаем" пользавателя шаблона в эти места. Может, есть возможность выдавать ошибку компиляции, если пользователь не внёс необходимые изменения, или, хотя бы, стоит кидать NotImplementedException?

2023-02-09 08:26 UTC, merged

2023-06-02 14:49 UTC, jva44ka commented
По замечаниям @Satem сделал пулреквест: https://github.com/Byndyusoft/byndyusoft-net-rabbitmqconsumer-template/pull/3