Добавил сбор метрик
Byndyusoft/byndyusoft-net-rabbitmqconsumer-template pull request #9
Opened 2023-09-04 04:29 UTC by Alex-Grigorichev

2023-09-04 12:41 UTC, AntonyNET requested changes

2023-09-04 12:41 UTC, AntonyNET commented on template/src/RabbitMqConsumerTemplate/Infrastructure/OpenTelemetry/ConsumerTemplateMetrics.cs
> +    public static readonly double[] DurationBuckets = { 5, 10, 20, 30, 60, 120, 180, 240, 300, 600, 900, 3600, 7200, 14400, 28800 };
почему выбранны именно такие бакеты? почему секунды?

2023-09-04 12:41 UTC, AntonyNET commented on template/src/RabbitMqConsumerTemplate/MessageHandler.cs
> +        var stopwatch = Stopwatch.StartNew();
почему на стопвотчах? почему не используется активити?

2023-09-04 12:41 UTC, AntonyNET commented on template/src/RabbitMqConsumerTemplate/MessageHandler.cs
> +        ConsumerTemplateMetrics.ObserveDuration(message!.Property, stopwatch.Elapsed);
зачем в теги вставлять свойство сообщения?

2023-09-04 12:41 UTC, AntonyNET commented on template/src/RabbitMqConsumerTemplate/Infrastructure/OpenTelemetry/ConsumerTemplateMetrics.cs
> +        HistogramDuration.Record(timeSpan.TotalSeconds, tagList);
хочется универсального решения, которое собирает метрики со всех очередей, со всех сервисов едино, чтобы потом было удобно строить графики. В качестве примера метрик можно глянуть http метрики неткора, как они единообразно собираются

2023-09-04 14:23 UTC, Alex-Grigorichev commented on template/src/RabbitMqConsumerTemplate/Infrastructure/OpenTelemetry/ConsumerTemplateMetrics.cs
> +    public static readonly double[] DurationBuckets = { 5, 10, 20, 30, 60, 120, 180, 240, 300, 600, 900, 3600, 7200, 14400, 28800 };
взял бакеты из шаблона апи

2023-09-04 14:46 UTC, Alex-Grigorichev commented on template/src/RabbitMqConsumerTemplate/Infrastructure/OpenTelemetry/ConsumerTemplateMetrics.cs
> +        HistogramDuration.Record(timeSpan.TotalSeconds, tagList);
Было бы не плохо, но это должно быть не в шаблоне а в самой либе рэаббита, предлагаю закинуть issue на это именно туда.

2023-09-04 14:53 UTC, Alex-Grigorichev commented on template/src/RabbitMqConsumerTemplate/MessageHandler.cs
> +        ConsumerTemplateMetrics.ObserveDuration(message!.Property, stopwatch.Elapsed);
Чтобы показать, что так можно делать.

2023-09-04 14:57 UTC, Alex-Grigorichev commented on template/src/RabbitMqConsumerTemplate/MessageHandler.cs
> +        var stopwatch = Stopwatch.StartNew();
Сделал по аналогии с шаблоном API.

2023-09-05 09:40 UTC, AntonyNET commented on template/src/RabbitMqConsumerTemplate/Infrastructure/OpenTelemetry/ConsumerTemplateMetrics.cs
> +    public static readonly double[] DurationBuckets = { 5, 10, 20, 30, 60, 120, 180, 240, 300, 600, 900, 3600, 7200, 14400, 28800 };
Не могу это принять, как аргумент. Звучит, как копипаст без раздумий

2023-09-05 09:41 UTC, AntonyNET commented on template/src/RabbitMqConsumerTemplate/MessageHandler.cs
> +        var stopwatch = Stopwatch.StartNew();
Не могу это принять, как аргумент. Звучит, как копипаст без раздумий

2023-09-05 09:41 UTC, AntonyNET commented on template/src/RabbitMqConsumerTemplate/MessageHandler.cs
> +        ConsumerTemplateMetrics.ObserveDuration(message!.Property, stopwatch.Elapsed);
для чего показывать опасное решение?

2023-09-05 09:42 UTC, AntonyNET commented on template/src/RabbitMqConsumerTemplate/Infrastructure/OpenTelemetry/ConsumerTemplateMetrics.cs
> +        HistogramDuration.Record(timeSpan.TotalSeconds, tagList);
А в чем тогда задача состояла? В ветке не указан номер карточки, поэтому не могу найти детали

2023-09-05 09:48 UTC, Alex-Grigorichev commented on template/src/RabbitMqConsumerTemplate/Infrastructure/OpenTelemetry/ConsumerTemplateMetrics.cs
> +        HistogramDuration.Record(timeSpan.TotalSeconds, tagList);
Задача на весь шаблон https://github.com/Byndyusoft/board-and-discussion/issues/35.
Отдельной задачи на сбор метрик нет.

2023-09-05 09:58 UTC, AntonyNET commented on template/src/RabbitMqConsumerTemplate/Infrastructure/OpenTelemetry/ConsumerTemplateMetrics.cs
> +        HistogramDuration.Record(timeSpan.TotalSeconds, tagList);
по ссылке нет никакого описания задачи и дода, не понимаю почему создан этот пр.

2023-09-05 10:04 UTC, Alex-Grigorichev commented on template/src/RabbitMqConsumerTemplate/Infrastructure/OpenTelemetry/ConsumerTemplateMetrics.cs
> +    public static readonly double[] DurationBuckets = { 5, 10, 20, 30, 60, 120, 180, 240, 300, 600, 900, 3600, 7200, 14400, 28800 };
Это шаблон, когда ты будешь создавать из него сервис, то сам определишь, какие тебе нужны бакеты и какие единицы измерения ты будешь использовать

2023-09-05 10:09 UTC, Alex-Grigorichev commented on template/src/RabbitMqConsumerTemplate/Infrastructure/OpenTelemetry/ConsumerTemplateMetrics.cs
> +        HistogramDuration.Record(timeSpan.TotalSeconds, tagList);
Потому что у нас есть требование к сервису на сбор телеметрии

2023-09-05 10:18 UTC, Alex-Grigorichev commented on template/src/RabbitMqConsumerTemplate/MessageHandler.cs
> +        ConsumerTemplateMetrics.ObserveDuration(message!.Property, stopwatch.Elapsed);
Чтобы юзер знал, что может прокинуть туда любое поле, которое ему надо туда прокинуть

2023-09-05 11:17 UTC, Alex-Grigorichev commented on template/src/RabbitMqConsumerTemplate/MessageHandler.cs
> +        var stopwatch = Stopwatch.StartNew();
Стопвотчи сильно проще и понятнее, чем подключение и использование инфры с активити.

2023-09-06 11:28 UTC, AntonyNET commented on template/src/RabbitMqConsumerTemplate/Infrastructure/OpenTelemetry/ConsumerTemplateMetrics.cs
> +        HistogramDuration.Record(timeSpan.TotalSeconds, tagList);
кинь ссылку где посмотреть требования задачи, которой ты занимаешься, чтобы я смог сопоставить пр и задачу

2023-09-06 12:33 UTC, Alex-Grigorichev commented on template/src/RabbitMqConsumerTemplate/Infrastructure/OpenTelemetry/ConsumerTemplateMetrics.cs
> +        HistogramDuration.Record(timeSpan.TotalSeconds, tagList);
Это не требования задачи, а требования к любому сервису (пункт на это есть в чеклисте проектов бэкэнда - https://disk.yandex.ru/edit/disk/disk%2F%2B%20Byndyusoft.%20Общие%20документы%2FЧеклисты%20проектных%20процессов%2FЧеклист%20проекта%20по%20бэкенду.xlsx?sk=y6d5b68e278d82fb84e94caa4e6c02dd5 17 пункт).

2023-09-07 05:35 UTC, AntonyNET approved these changes
Так и не понял, почему нужен этот пр.
Мне он не нравится, но ставлю апрув, так как Саша говорит, что все ок

2023-09-07 08:46 UTC, merged